---
title: "data_EDA"
author: "yz5248"
date: "2025-10-02"
output: github_document
---
```{r}
library(p8105.datasets)
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
data("weather_df")

weather_df = 
  weather_df |>
  mutate(month = floor_date(date, unit = "month"))
```

make plots

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```


check on extreme values
```{r}
weather_df |> 
  filter(prcp > 1000)
```

look at data again
```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point()
```

```{r}
weather_df |>
  group_by(name, month)
```

```{r}
weather_df |>
  group_by(name) |>
  summarize(
    n = n()
    )
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    n = n()
  )
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```

```{r}
weather_df |>
  count(name)
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  ) |> view()
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |>
  ggplot(aes(x = month, y = mean_tmax, colour = name)) +
  geom_point() +
  geom_line()
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |>
  knitr::kable(digits = 2)
```

##mutate with groups
```{r}
weather_df |>
  group_by(name) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) |> 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

```{r}
weather_df |>
  group_by(name, month) |>
  mutate(temp_rank = min_rank(tmax)) |>
  filter(temp_rank < 2)
```

```{r}
weather_df |>
  group_by(name, month) |>
  mutate(temp_rank = min_rank(desc(tmin))) |>
  view()
```

what about lags?
```{r}
weather_df |>
  group_by(name) |>
  mutate(lagged_tmax = lag(tmax))
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax)) |>
  summarize(
    temp_change_sd = sd(temp_change, na.rm = TRUE),
    temp_change_max = max(temp_change, na.rm = TRUE))
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    temp_change = tmax - lag(tmax)
    )|>
  filter(
     min_rank(desc(temp_change))<2
  )
```

